# -*- coding: utf-8 -*-
"""data_cleaning_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1empA1srSLipAIWPkdSgsCOQvMWKtf_iS

# Data Cleaning Pipeline: Abnormal Listing Detection & Product Recommendation

Notebook นี้ทำความสะอาดและเตรียมข้อมูลให้พร้อมสำหรับโมเดล AI จาก 2 ชุดข้อมูล:

1. **`dataset_abnormal_listing.xlsx`** — AI Abnormal Listing Detection (ตรวจจับประกาศขายสินค้าผิดปกติ)
2. **`dataset_recommendation.xlsx`** — Product Recommendation System

**วิธีใช้:** วางไฟล์ทั้งสองไว้ในโฟลเดอร์ `data/` (ข้างๆ ไฟล์ notebook นี้) แล้วรันทีละเซลล์ตามลำดับ
หากไฟล์ของคุณชื่ออื่น ให้แก้ตัวแปร `FILE_1` และ `FILE_2` ในเซลล์ Setup ด้านล่าง

Output: ไฟล์ CSV ที่ทำความสะอาดแล้ว จะถูกเซฟไว้ในโฟลเดอร์ `output/`

## 0. Setup
"""

import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

import pandas as pd
import numpy as np
import re
import os
import emoji

pd.set_option('display.max_columns', 60)
pd.set_option('display.width', 200)

FILE_1 = "data/dataset_abnormal_listing.xlsx"   # Abnormal Listing Detection
FILE_2 = "data/dataset_recommendation.xlsx"     # Product Recommendation

OUTPUT_DIR = "output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

"""---
# PART 1 — Abnormal Listing Detection Dataset

โครงสร้างไฟล์: `1_Data_Dictionary`, `2_Business_Rules`, `3_Training_Dataset`,
`4_Validation_Dataset`, `5_Testing_Dataset`, `6_UAT_Dataset`, `7_Coverage_Matrix`, `8_Acceptance_Criteria`

แต่ละชีทข้อมูล (Training/Validation/Testing/UAT) มี header อยู่ที่แถวที่ 5 ของ Excel (index 4)

"""

xl1 = pd.ExcelFile(FILE_1)
print(xl1.sheet_names)

# โหลด Business Rules และ Data Dictionary ไว้อ้างอิงระหว่างทำความสะอาด
bus_rules_1 = xl1.parse("2_Business_Rules", header=3)
data_dict_1 = xl1.parse("1_Data_Dictionary", header=3)
bus_rules_1

def load_listing_sheet(sheet_name):
    df = xl1.parse(sheet_name, header=4)
    df["__source_sheet__"] = sheet_name
    return df

train_raw = load_listing_sheet("3_Training_Dataset")
val_raw   = load_listing_sheet("4_Validation_Dataset")
test_raw  = load_listing_sheet("5_Testing_Dataset")
uat_raw   = load_listing_sheet("6_UAT_Dataset")

for name, df in [("train", train_raw), ("val", val_raw), ("test", test_raw), ("uat", uat_raw)]:
    print(name, df.shape)

"""### 1.1 รวมชุดข้อมูลชั่วคราวเพื่อทำความสะอาดพร้อมกัน

รวมทั้ง 4 ชุดเข้าด้วยกันก่อน (มี `__source_sheet__` กำกับไว้) เพื่อให้ทำความสะอาดครั้งเดียว
แล้วค่อยแยกกลับตามชุดเดิมตอนท้าย — วิธีนี้การันตีว่ากติกาทำความสะอาดเหมือนกันทุกชุด

"""

listing_all = pd.concat([train_raw, val_raw, test_raw, uat_raw], ignore_index=True)
print(listing_all.shape)
listing_all.head(3)

"""### 1.2 ตรวจสอบ null ที่ตั้งใจ (intentional) vs ที่ไม่ตั้งใจ

ตาม Data Dictionary ค่า null ใน `Product_Name`, `Condition`, `Price`, `Marketplace_Average_Price`,
`Price_Deviation_Percentage` ส่วนหนึ่งเป็น **NEGATIVE test case ที่จงใจใส่ไว้เพื่อทดสอบ** —
ห้ามลบทิ้งหรือ impute ทับโดยไม่เช็ค `Scenario_Type` ก่อน

"""

null_cols = listing_all.columns[listing_all.isna().any()].tolist()
print("คอลัมน์ที่มี null:", null_cols)

for col in null_cols:
    null_mask = listing_all[col].isna()
    print(f"\n--- {col}: null ทั้งหมด {null_mask.sum()} แถว ---")
    print(listing_all.loc[null_mask, "Scenario Type"].value_counts())

# แยกธง is_intentional_null เก็บไว้ ไม่ลบแถว NEGATIVE ทิ้ง
# แต่ถ้า null เกิดขึ้นนอก scenario NEGATIVE/EDGE ให้ถือเป็น data quality issue จริง
INTENTIONAL_NULL_SCENARIOS = {"NEGATIVE", "EDGE"}

listing_all["is_intentional_null"] = listing_all["Scenario Type"].isin(INTENTIONAL_NULL_SCENARIOS)

unexpected_nulls = listing_all[
    listing_all[null_cols].isna().any(axis=1) & ~listing_all["is_intentional_null"]
]
print(f"แถวที่มี null แบบไม่ควรมี (นอก NEGATIVE/EDGE): {len(unexpected_nulls)}")
unexpected_nulls[["Dataset ID", "Scenario Type"] + null_cols].head(10)

"""> ถ้าเจอ unexpected null (นอกกลุ่ม NEGATIVE/EDGE) ให้ตัดสินใจเป็นรายคอลัมน์ เช่น
> impute ด้วยค่ากลาง (median) สำหรับตัวเลข หรือ mode สำหรับ categorical — ในที่นี้จะ impute แบบระมัดระวัง
"""

numeric_impute_cols = ["Price", "Marketplace Average Price", "Price Deviation Percentage"]
for col in numeric_impute_cols:
    if col in unexpected_nulls.columns and len(unexpected_nulls) > 0:
        median_val = listing_all.loc[~listing_all["is_intentional_null"], col].median()
        fix_mask = listing_all[col].isna() & ~listing_all["is_intentional_null"]
        listing_all.loc[fix_mask, col] = median_val

if "Product Name" in listing_all.columns:
    fix_mask = listing_all["Product Name"].isna() & ~listing_all["is_intentional_null"]
    listing_all.loc[fix_mask, "Product Name"] = (
        listing_all.loc[fix_mask, "Brand"].fillna("") + " " + listing_all.loc[fix_mask, "Model"].fillna("")
    ).str.strip()

print("เหลือ null นอก intentional case:",
      listing_all.loc[~listing_all["is_intentional_null"], null_cols].isna().sum().sum())

"""### 1.3 ทำความสะอาดข้อความ (Title / Description)

ข้อความมีภาษาไทยปนอังกฤษ, emoji, ช่องว่างซ้ำ, ตัวอักษรพิเศษ — normalize ให้ใช้งานง่ายขึ้น
แต่ **เก็บ emoji/สัญลักษณ์ไว้เป็นฟีเจอร์แยก** ก่อนลบออกจากข้อความหลัก เพราะมันอาจสัมพันธ์กับ Spam/Suspicious_Word

"""

def extract_and_clean_text(series):
    def remove_emoji(text):
        return emoji.replace_emoji(text, replace='')

    def check_emoji(text):
        return emoji.emoji_count(text) > 0

    has_emoji = series.fillna("").apply(check_emoji)
    cleaned = series.fillna("").apply(remove_emoji)
    cleaned = cleaned.str.replace(r"\s+", " ", regex=True).str.strip()
    return cleaned, has_emoji

listing_all["Title_clean"], listing_all["Title_has_emoji"] = extract_and_clean_text(listing_all["Title"])
listing_all["Description_clean"], listing_all["Description_has_emoji"] = extract_and_clean_text(listing_all["Description"])

listing_all["Title_has_emoji"] = listing_all["Title_has_emoji"].astype(int)
listing_all["Description_has_emoji"] = listing_all["Description_has_emoji"].astype(int)

listing_all["Title_length"] = listing_all["Title_clean"].str.len()
listing_all["Description_length"] = listing_all["Description_clean"].str.len()

listing_all[["Title", "Title_clean", "Title_has_emoji", "Title_length"]].head(5)

"""### 1.4 Encode ฟีเจอร์ Yes/No → 0/1

คอลัมน์ flag เกือบทั้งหมดเป็น string 'Yes'/'No' — encode เป็นตัวเลขให้พร้อมเข้าโมเดล

"""

yesno_cols = [
    "Duplicate Image", "Duplicate Title", "Image Match Category", "AI Image Detected",
    "Keyword Stuffing", "Suspicious Word", "Profanity", "Adult Content",
    "Illegal Product", "Counterfeit", "Category Mismatch",
    "Title Description Mismatch", "Spam Behavior",
]
yesno_cols = [c for c in yesno_cols if c in listing_all.columns]

for col in yesno_cols:
    listing_all[col + "_flag"] = listing_all[col].map({"Yes": 1, "No": 0})

listing_all[yesno_cols[:3] + [c + "_flag" for c in yesno_cols[:3]]].head(5)

"""### 1.5 ตรวจสอบขอบเขตค่า (range validation) ตาม Data Dictionary

- `Seller_Rating`: 0.0–5.0
- `Risk_Score`: 0–100
- `Confidence_Score`: 0.00–1.00
- `Price`, `Marketplace_Average_Price`: >= 0

"""

range_checks = {
    "Seller Rating": (0.0, 5.0),
    "Risk Score": (0, 100),
    "Confidence Score": (0.0, 1.0),
}

for col, (lo, hi) in range_checks.items():
    out_of_range = ~listing_all[col].between(lo, hi)
    print(f"{col}: {out_of_range.sum()} แถวหลุดขอบเขต [{lo}, {hi}]")

# Price ต้อง >= 0 (ยกเว้น null ที่เป็น intentional)
neg_price = (listing_all["Price"] < 0)
print("Price ติดลบ:", neg_price.sum())

"""### 1.6 Encode categorical columns สำหรับโมเดล

- Label encode / one-hot สำหรับ `Category`, `Condition`, `Image Quality`
- เก็บ label เป้าหมาย `Ground Truth` และ `Expected Result` แยกไว้ไม่ปนกับฟีเจอร์

"""

categorical_cols = ["Category", "Subcategory", "Condition", "Image Quality"]
categorical_cols = [c for c in categorical_cols if c in listing_all.columns]

# เก็บชื่อคอลัมน์ก่อน encode ไว้ เพื่อคำนวณว่าคอลัมน์ dummy ใหม่ๆ มีอะไรบ้าง
# (แม่นยำกว่าการเดาด้วย substring match ซึ่งอาจชนกับคอลัมน์อื่น เช่น 'Category_Mismatch')
cols_before = set(listing_all.columns)
listing_encoded = pd.get_dummies(listing_all, columns=categorical_cols, prefix=categorical_cols)
dummy_cols_listing = [c for c in listing_encoded.columns if c not in cols_before]

print("Shape หลัง one-hot encode:", listing_encoded.shape)
print(f"จำนวนคอลัมน์ dummy ที่สร้างใหม่: {len(dummy_cols_listing)}")

"""### 1.7 แยกฟีเจอร์ (X) และ label (y) พร้อมแยกกลับเป็น Train/Val/Test/UAT ตามเดิม"""

FEATURE_COLS = (
    [c for c in listing_encoded.columns if c.endswith("_flag")]
    + dummy_cols_listing
    + ["Price", "Marketplace Average Price", "Price Deviation Percentage",
       "Seller Rating", "Seller Total Listings", "Seller Violation Count",
       "Title_length", "Description_length", "Title_has_emoji", "Description_has_emoji"]
)
FEATURE_COLS = [c for c in FEATURE_COLS if c in listing_encoded.columns and c not in ["Risk Band", "Risk Score", "Ground Truth", "Expected Result"]]

LABEL_COLS = ["Ground Truth", "Expected Result", "Risk Score", "Risk Band"]

print(f"จำนวนฟีเจอร์: {len(FEATURE_COLS)}")

cleaned_splits = {}
for sheet, name in [("3_Training_Dataset", "train"), ("4_Validation_Dataset", "val"),
                     ("5_Testing_Dataset", "test"), ("6_UAT_Dataset", "uat")]:
    subset = listing_encoded[listing_encoded["__source_sheet__"] == sheet].copy()
    cleaned_splits[name] = subset
    out_path = os.path.join(OUTPUT_DIR, f"listing_{name}_clean.csv")
    subset.to_csv(out_path, index=False, encoding="utf-8-sig")
    print(f"{name}: {subset.shape} -> {out_path}")

print("✅ Data Cleaning Pipeline เสร็จสมบูรณ์! พร้อมนำไฟล์ .csv ไปใช้ใน prepare_safety_dataset.py ต่อไป")
